option('archive', type : 'boolean', value : true, description : 'Build with libarchive.')
option('direct3d', type : 'boolean', value : true, description : 'Build with Direct3D 11 support.')
option('fontconfig', type : 'boolean', value : true, description : 'Build with fontconfig if available.')
option('force_inline_shaders', type : 'boolean', value : false, description : 'Put shaders in the executable.')
option('ftp', type : 'boolean', value : true, description : 'Build with FTP support.')
option('gnutls', type : 'boolean', value : true, description : 'Build with gnutls if available.')
option('icu', type : 'boolean', value : true, description : 'Build with ICU.')
option('mupdf', type : 'boolean', value : true, description : 'Build with MuPDF support.')
option('native', type : 'boolean', value : false, description : 'Build for the current CPU.')
option('opengl', type : 'boolean', value : true, description : 'Build with OpenGL 1.1, 3.0 and ES 3.0 support.')
option('openssl', type : 'boolean', value : true, description : 'Build with openssl if available.')
option('poppler', type : 'boolean', value : true, description : 'Build with Poppler support.')
option('sdl3', type : 'boolean', value : false, description : 'Build with SDL3')
option('secret', type : 'boolean', value : true, description : 'Build with libsecret if available.')
option('smbclient', type : 'boolean', value : true, description : 'Build with smbclient if available.')
option('ssh2', type : 'boolean', value : true, description : 'Build with libssh2 if available.')
option('vulkan', type : 'boolean', value : true, description : 'Build with Vulkan 1.0 support.')
