#pragma once

// directory separator
#ifdef _WIN32
const char dsep = '\\';
#else
const char dsep = '/';
#endif

// general settings
#define DEFAULT_LANGUAGE "english"

// video settings
#define DEFAULT_RESOLUTION	vec2i(800, 600)
#define DEFAULT_FONT		"arial"

// colors
#define DEFAULT_COLOR_BACKGROUND	vec4c(10, 10, 10, 255)
#define DEFAULT_COLOR_RECTANGLE		vec4c(90, 90, 90, 255)
#define DEFAULT_COLOR_HIGHLIGHTED	vec4c(120, 120, 120, 255)
#define DEFAULT_COLOR_DARKENED		vec4c(60, 60, 60, 255)
#define DEFAULT_COLOR_TEXT			vec4c(210, 210, 210, 255)

// audio settings
#define DEFAULT_MUSIC_VOL  128
#define DEFAULT_SOUND_VOL  0
#define DEFAULT_SONG_DELAY 0.5f

// controls settings
#define DEFAULT_SCROLL_SPEED vec2f(4.f, 8.f)
#define DEFAULT_DEADZONE	 256

// shortcut names
#define SHORTCUT_OK				"ok"
#define SHORTCUT_BACK			"back"
#define SHORTCUT_ZOOM_IN		"zoom_in"
#define SHORTCUT_ZOOM_OUT		"zoom_out"
#define SHORTCUT_ZOOM_RESET		"zoom_reset"
#define SHORTCUT_CENTER_VIEW	"center_view"
#define SHORTCUT_FAST			"fast"
#define SHORTCUT_SLOW			"slow"
#define SHORTCUT_PLAY_PAUSE		"play_pause"
#define SHORTCUT_FULLSCREEN		"fullscreen"
#define SHORTCUT_NEXT_DIR		"next_dir"
#define SHORTCUT_PREV_DIR		"prev_dir"
#define SHORTCUT_NEXT_SONG		"next_song"
#define SHORTCUT_PREV_SONG		"prev_song"
#define SHORTCUT_VOLUME_UP		"volume_up"
#define SHORTCUT_VOLUME_DOWN	"volume_down"
#define SHORTCUT_PAGE_UP		"page_up"
#define SHORTCUT_PAGE_DOWN		"page_down"
#define SHORTCUT_UP				"up"
#define SHORTCUT_DOWN			"down"
#define SHORTCUT_RIGHT			"right"
#define SHORTCUT_LEFT			"left"
#define SHORTCUT_CURSOR_UP		"cursor_up"
#define SHORTCUT_CURSOR_DOWN	"cursor_down"
#define SHORTCUT_CURSOR_RIGHT	"cursor_right"
#define SHORTCUT_CURSOR_LEFT	"cursor_left"

// key bindings
#define DEFAULT_KEY_OK				SDL_SCANCODE_RETURN
#define DEFAULT_KEY_BACK			SDL_SCANCODE_ESCAPE
#define DEFAULT_KEY_ZOOM_IN			SDL_SCANCODE_E
#define DEFAULT_KEY_ZOOM_OUT		SDL_SCANCODE_Q
#define DEFAULT_KEY_ZOOM_RESET		SDL_SCANCODE_R
#define DEFAULT_KEY_CENTER_VIEW		SDL_SCANCODE_C
#define DEFAULT_KEY_FAST			SDL_SCANCODE_LSHIFT
#define DEFAULT_KEY_SLOW			SDL_SCANCODE_LALT
#define DEFAULT_KEY_PLAY_PAUSE		SDL_SCANCODE_SPACE
#define DEFAULT_KEY_FULLSCREEN		SDL_SCANCODE_L

#define DEFAULT_KEY_NEXT_DIR		SDL_SCANCODE_P
#define DEFAULT_KEY_PREV_DIR		SDL_SCANCODE_O

#define DEFAULT_KEY_NEXT_SONG		SDL_SCANCODE_D
#define DEFAULT_KEY_PREV_SONG		SDL_SCANCODE_A
#define DEFAULT_KEY_VOLUME_UP		SDL_SCANCODE_W
#define DEFAULT_KEY_VOLUME_DOWN		SDL_SCANCODE_S

#define DEFAULT_KEY_PAGE_UP			SDL_SCANCODE_PAGEUP
#define DEFAULT_KEY_PAGE_DOWN		SDL_SCANCODE_PAGEDOWN
#define DEFAULT_KEY_UP				SDL_SCANCODE_UP
#define DEFAULT_KEY_DOWN			SDL_SCANCODE_DOWN
#define DEFAULT_KEY_RIGHT			SDL_SCANCODE_RIGHT
#define DEFAULT_KEY_LEFT			SDL_SCANCODE_LEFT

// joystick bindings
#define DEFAULT_JBUTTON_OK			2
#define DEFAULT_JBUTTON_BACK		1
#define DEFAULT_JBUTTON_ZOOM_IN		5
#define DEFAULT_JBUTTON_ZOOM_OUT	4
#define DEFAULT_JBUTTON_ZOOM_RESET	11
#define DEFAULT_JBUTTON_CENTER_VIEW	10
#define DEFAULT_JBUTTON_FAST		0
#define DEFAULT_JBUTTON_SLOW		3
#define DEFAULT_JBUTTON_PLAY_PAUSE	9
#define DEFAULT_JBUTTON_FULLSCREEN	8

#define DEFAULT_JBUTTON_NEXT_DIR	7
#define DEFAULT_JBUTTON_PREV_DIR	6

#define DEFAULT_JHAT_DPAD_RIGHT		SDL_HAT_RIGHT
#define DEFAULT_JHAT_DPAD_LEFT		SDL_HAT_LEFT
#define DEFAULT_JHAT_DPAD_UP		SDL_HAT_UP
#define DEFAULT_JHAT_DPAD_DOWN		SDL_HAT_DOWN

#define DEFAULT_JAXIS_VERTICAL		1
#define DEFAULT_JAXIS_HORIZONTAL	0
#define DEFAULT_JAXIS_CURSOR_VERT	3
#define DEFAULT_JAXIS_CURSOR_HORI	2

// gamepad bindings
#define DEFAULT_GBUTTON_OK			SDL_CONTROLLER_BUTTON_A
#define DEFAULT_GBUTTON_BACK		SDL_CONTROLLER_BUTTON_B
#define DEFAULT_GBUTTON_ZOOM_IN		SDL_CONTROLLER_BUTTON_RIGHTSHOULDER
#define DEFAULT_GBUTTON_ZOOM_OUT	SDL_CONTROLLER_BUTTON_LEFTSHOULDER
#define DEFAULT_GBUTTON_ZOOM_RESET	SDL_CONTROLLER_BUTTON_RIGHTSTICK
#define DEFAULT_GBUTTON_CENTER_VIEW	SDL_CONTROLLER_BUTTON_LEFTSTICK
#define DEFAULT_GBUTTON_FAST		SDL_CONTROLLER_BUTTON_Y
#define DEFAULT_GBUTTON_SLOW		SDL_CONTROLLER_BUTTON_X
#define DEFAULT_GBUTTON_PLAY_PAUSE	SDL_CONTROLLER_BUTTON_START
#define DEFAULT_GBUTTON_FULLSCREEN	SDL_CONTROLLER_BUTTON_BACK

#define DEFAULT_GAXIS_NEXT_DIR		SDL_CONTROLLER_AXIS_TRIGGERRIGHT
#define DEFAULT_GAXIS_PREV_DIR		SDL_CONTROLLER_AXIS_TRIGGERLEFT

#define DEFAULT_GBUTTON_DPAD_RIGHT	SDL_CONTROLLER_BUTTON_DPAD_RIGHT
#define DEFAULT_GBUTTON_DPAD_LEFT	SDL_CONTROLLER_BUTTON_DPAD_LEFT
#define DEFAULT_GBUTTON_DPAD_UP		SDL_CONTROLLER_BUTTON_DPAD_UP
#define DEFAULT_GBUTTON_DPAD_DOWN	SDL_CONTROLLER_BUTTON_DPAD_DOWN

#define DEFAULT_GAXIS_VERTICAL		SDL_CONTROLLER_AXIS_LEFTY
#define DEFAULT_GAXIS_HORIZONTAL	SDL_CONTROLLER_AXIS_LEFTX
#define DEFAULT_GAXIS_CURSOR_VERT	SDL_CONTROLLER_AXIS_RIGHTY
#define DEFAULT_GAXIS_CURSOR_HORI	SDL_CONTROLLER_AXIS_RIGHTX

// other controller bindings related stuff
#define DEFAULT_JHAT_ID			0
#define DEFAULT_AXIS_DIR_UP		false
#define DEFAULT_AXIS_DIR_DOWN	true
#define DEFAULT_AXIS_DIR_RIGHT	true
#define DEFAULT_AXIS_DIR_LEFT	false

// program constants
const float normalScrollFactor = 100.f;
const float fastScrollFactor = normalScrollFactor * 4.f;
const float slowScrollFactor = normalScrollFactor / 2.f;
const float normalMDragFactor = 300.f;
const float fastMDragFactor = normalMDragFactor * 4.f;
const float slowMDragFactor = normalMDragFactor / 4.f;
const float zoomFactor = 1.2f;
