#version 460

layout(local_size_x = 32) in;

layout(push_constant) uniform PushData {
	uint offset;
} psData;

layout(set = 0, binding = 0) readonly buffer InputData {
	uint pixels[];
} inData;

layout(set = 0, binding = 1) writeonly buffer OutputData {
	uint pixels[];
} outData;

layout(set = 0, binding = 2) uniform UniformData {
	uvec4 colors[256 / 4];
} ud;

#define getColor(pid) ud.colors[(pid) / 4][(pid) % 4]

void main() {
	uint iid = (gl_WorkGroupID.x + psData.offset) * gl_WorkGroupSize.x + gl_LocalInvocationID.x;
	uint oid = iid * 4;
	uint px = inData.pixels[iid];

	outData.pixels[oid] = getColor(px & 0xFF);
	outData.pixels[oid + 1] = getColor((px >> 8) & 0xFF);
	outData.pixels[oid + 2] = getColor((px >> 16) & 0xFF);
	outData.pixels[oid + 3] = getColor(px >> 24);
}
